# FellScout behind Apache
#
# Use auth_basic to authenticate the users, and
# proxy back to the `web` service on localhost:5001
#
# The `RequestHeader set` line forces overwriting of
# X-Remote-User, so ensuring users can't impersonate
# each other.
#
# Needs some apache modules:
#
#    a2enmod proxy proxy_http headers auth_basic authn_file
#
# And to create some users:
#
#    htpasswd -c /etc/apache2/fellscout-htpasswd <username>
#
# Be careful to omit the `-c` when any users already exist!

<VirtualHost *:80>
	ServerName fellscout.example.org

	ProxyPass        / http://127.0.0.1:5001/
	ProxyPassReverse / http://127.0.0.1:5001/

	<Location />
		AuthType Basic
		AuthName "Fell Scout"
		AuthUserFile /etc/apache2/fellscout-htpasswd
		Require valid-user
	</Location>

	RequestHeader set X-Remote-User "expr=%{REMOTE_USER}"
</VirtualHost>
