# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "FellScout"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"

logger: "File"
engines:
  session:
    Simple:
      cookie_name: FellScout
  logger:
    File:
      log_dir: "/home/avi/logs/"
      file_name: "fellscout.log"
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag: '%>'
progress_csv_path: progress.csv
commands:
  progress_to_json_args: --teams --entrants


plugins:
  Database:
    driver: 'mysql'
    connection_check_threshold: 10
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
    on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
    log_queries: 1
