requires "Dancer2" => "0.208001";
requires "YAML" => "0";

recommends "YAML"             => "0";
recommends "URL::Encode::XS"  => "0";
recommends "CGI::Deurl::XS"   => "0";
recommends "HTTP::Parser::XS" => "0";

on "test" => sub {
    requires "Test::More"            => "0";
    requires "HTTP::Request::Common" => "0";
    requires "Plack::Test"           => "0";
    requires "Ref::Util"             => "0";
    requires "JSON"                  => "0";
    requires "DBI"                   => "0";
    requires "DBD::MariaDB"          => "0";
};

# progress-to-json
requires "Text::CSV" => "0";
requires "Time::Local" => "0"